### ISSUE TITLE
Is the base plate file at the bottom uploaded incorrectly? The stl file is the top cover

### ISSUE THREAD

**Issue by alaosion2019** [ros-acceleration/robotic_processing_unit#1]

**Comment by vmayoral** [comment]
Thanks for reporting. That's right. Seems a glitch in the last commit there. Base is fine at this point https://github.com/ros-acceleration/robotic_processing_unit/commits/f9e813b2820f75fe3d9a27a4bfe5ab5d45029536/mechanical.

Find the base at https://github.com/ros-acceleration/robotic_processing_unit/blob/f9e813b2820f75fe3d9a27a4bfe5ab5d45029536/mechanical/robotic_processing_unit_base.stl.

Fixed at https://github.com/ros-acceleration/robotic_processing_unit/commit/80d6307d1e6a8e631dbf5da2f4ea4a918f244b11
