### ISSUE TITLE
File too small -- no dimensions known 

### ISSUE THREAD

**Issue by abigdreamer** [ros-acceleration/robotic_processing_unit#2]
The size is not clear. Or the ratios or anything.
The file is really tiny and nowhere does it tell us what size it is.

**Comment by vmayoral** [comment]
Files come out just fine for us when we 3D-printed them. They should be ready for this without any scaling. Not sure which software you're using though. You may want to leave note of this for future users.

![imagen](https://github.com/ros-acceleration/robotic_processing_unit/assets/1375246/95787747-ad2f-4ac6-8560-d552ccbfeb68)
![imagen](https://github.com/ros-acceleration/robotic_processing_unit/assets/1375246/74d3a25e-5fe1-4c2c-a60e-1f1be86a5883)
![imagen](https://github.com/ros-acceleration/robotic_processing_unit/assets/1375246/ef080c7b-5d12-4ce0-aec4-0bddcfcaeb3d)

Some more public information on this is also available at https://accelerationrobotics.com/robotcore.php, which contains a commercial version of the Robotic Processing Unit.
